### ISSUE TITLE
default values for tuning parameters should be within range

### ISSUE THREAD

**Issue by lukasal** [tidymodels/dials#153]
## The problem

The default value for parameters should be within range, as otherwise out of range values are selected (e.g. in value_seq_int and value_seq_double when levels == 1), but also everywhere else where the default is accessed.

## Reproducible example

```r
library(tidymodels)
param <- under_ratio(range = c(12,13))
param$default
# the value is 1, it should been something between 12,13
grid_regular(param,levels = 1)
# with the randomized grid it works
grid_random(param,size = 1)

reprex::reprex(si = TRUE)
```

**Comment by juliasilge** [comment]
It looks like you may have had trouble getting started with reprex; take a [look at this article for a walk-through](https://reprex.tidyverse.org/articles/articles/magic-reprex.html) of how to use it.

``` r
library(dials)
#> Loading required package: scales

param <- under_ratio(range = c(12, 13))
param$default
#> [1] 1

grid_regular(param, levels = 1)
#> # A tibble: 1 x 1
#>   under_ratio
#>         <dbl>
#> 1           1

grid_random(param, size = 1)
#> # A tibble: 1 x 1
#>   under_ratio
#>         <dbl>
#> 1        12.7
```

<sup>Created on 2021-02-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


This is happening because in `value_seq_dbl()`, this first condition is evaluating to `TRUE` and the object default is being used:

https://github.com/tidymodels/dials/blob/6e939ff4ca3906972c131c92c6dfa52226f932ce/R/aaa_values.R#L142

What we want to happen is to get down to this `else` instead:

https://github.com/tidymodels/dials/blob/6e939ff4ca3906972c131c92c6dfa52226f932ce/R/aaa_values.R#L147-L153
