### ISSUE TITLE
Use functions rather than objects for parameter creation

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/dials#17]
i.e. something like `new_neighbors()` rather than having a `neighbors` object immediately available?

**Comment by topepo** [comment]
I like `neighbors()` better.

**Comment by zenggyu** [comment]
@DavisVaughan @topepo  Will you consider bundling all the existing param objects in `new_quant_param()`/`new_qual_param()` as templates and then add a new argument to the functions to generate the objects? For example:

```
neighbors <- new_quant_param(template = "neighbors")
```

In my opinion this will make the package environment much cleaner.

**Comment by topepo** [comment]
This work is largely done and ready to go to CRAN. 

@zenggyu: probably not. The reason is that the code to do that is probably 2-3x the size of the code to create it form scratch. For example, using the constructor functions (i.e. `new_quant_param()`), a new parameter definition tends to be around 10 lines of code.
