### ISSUE TITLE
sample_size()

### ISSUE THREAD

**Issue by Steviey** [tidymodels/dials#175]
_**dials 0.0.9, modeltime latest, model: prophet_boost**_

Fix: https://github.com/tidymodels/dials/issues/111
seems not to include finalizing the whole enchilada at once...

```
finalParams <- modelObj %>% parameters() %>% 
                    finalize(x=trainPart) 
```
I'll do this (looks ugly):

`finalParams<-finalParams %>% update(sample_size = sample_prop(c(0.4, 0.9)))`

cu

**Comment by juliasilge** [comment]
Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) to show what kind of problem you are having with `dials::sample_size()`? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it.

If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You may already have reprex installed (it comes with the tidyverse package), but if not you can install it with:

```r
install.packages("reprex")
```

Thanks! 🙌
