### ISSUE TITLE
Cannot coerce class ‘c("rand_forest", "model_spec")’ to a data.frame

### ISSUE THREAD

**Issue by adschwab1** [tidymodels/dials#95]
Keep running into this error using dials 0.0.4. Did the merge function for dials become deprecated for merging a parsnip model object with a hyperparameter grid?

**Comment by topepo** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.

**Comment by topepo** [comment]
closed due to inactivity.
